---
- name: install memcached
  yum: name=memcached state=present
  tags:
    - memcached
    - packages

- name: configure memcached
  template: src=sysconfig.j2 dest=/etc/sysconfig/memcached owner=root group=root mode=0644
  notify: restart memcached
  tags:
    - memcached
    - configuration

- name: ensure memcached is enabled and running
  service: name=memcached enabled=yes state=started
  tags:
    - memcached
    - configuration
    - services

- name: configure firewalld for memcached
  firewalld: zone=public port="{{ memcached_port }}/tcp" permanent=true state=enabled
  notify: reload firewall
  when: memcached_open_port and ansible_distribution_major_version|int > 6
  tags:
    - memcached
    - firewall
    - configuration
